# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '36fed0cd-9f36-4244-b32d-025947295f72'
  dockerfilePath: '$(Build.SourcesDirectory)/src/store-front/Dockerfile'
  containerRegistry: 'acrakstestsouthcentralus.azurecr.io'
  imageRepository: 'aksstorefrontdemo'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: '$(imageRepository)'
        dockerfile: '$(dockerfilePath)'
        containerRegistry: '$(dockerRegistryServiceConnection)'
        tags: |
          $(tag)
    
    - task: Bash@3
      inputs: 
        targetType: 'inline'
        script: |
        echo 'Helloworld from Azure DevOps Pipeline'
