apiVersion: v1
kind: Service
metadata:
    name: devenergyaisolutionsaksstoredemo
spec:
    type: LoadBalancer
    ports:
    - port: 5001 
    selector:
        app: devenergyaisolutionsaksstoredemo